import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";
import Navbar from "~/components/navbar/Navbar";
import { useWeb3Token } from "~/hooks/useWeb3Token";
import Hero from "./components/Landing/Hero";
import AllTokens from "./components/Landing/AllTokens";

const Home: NextPage = () => {
  const { token } = useWeb3Token();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative min-h-screen pb-32">
        <div
          className="absolute top-0 left-0 h-[300px] w-[240px] bg-gradient-to-br from-[#3D4045] via-transparent to-[#27272A]"
          style={{
            backgroundImage:
              "linear-gradient(to bottom right, #3D4045 30%, #27272A 30%)",
          }}
        ></div>
        <Navbar />
        <div className="relative z-10 mx-auto mt-20 max-w-7xl">
          <div className="grid grid-cols-2 gap-20">
            <div className="col-span-2 self-center sm:col-span-1">
              <h1 className="font-inter text-5xl font-black text-white">
                <span className="block">Stay on Top of the Latest</span>
                <span className="block">Crypto health News</span>
              </h1>
              <p className="mt-8 w-2/3 font-display text-lg font-normal leading-5 text-white opacity-60">
                Subscribe to your favorite crypto tokens to get latest news on
                them everyday. No more no less!
              </p>
            </div>
            <div className="col-span-1 rounded-xl bg-[#1A1B1F] p-10 drop-shadow-xl">
              <p className="text-white opacity-60">Briefing for</p>
              <h1 className="mt-2 font-display text-5xl font-black text-white">
                <span className="block">5th March</span>
                <span className="block">2023</span>
              </h1>
              <div className="flex justify-end">
                <button className="cursor-pointer rounded-xl bg-[#FF5CAA] py-4 px-8 font-display text-white">
                  Check the Area
                </button>
              </div>
            </div>
          </div>
          {!token ? <Hero /> : <AllTokens />}
        </div>
      </main>
    </>
  );
};

export default Home;

// const AuthShowcase: React.FC = () => {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined }
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// };
